### ISSUE TITLE
error: linking with `arm-linux-musleabihf-gcc` failed: exit status: 1

### ISSUE THREAD

**Issue by dwhiteddsoft** [cross-rs/cross#604] opened 2021-11-02 04:14 UTC
How do you begin to debug these type of errors? From one directory it builds fine and from another it does not. What I was trying to do was test my GitHub Action Pipeline. On my machine, no sweat. In GH Action - FAIL. Started by doing a custom runner so I could get it to run on a machine I can control. Same results. The clone of the repo compiles fine, the _worker directory source does not. I had a similiar issue once and it was the underlying docker container and file permission. I cant seem to get "underneath" this one though. Error is below:

```
error: linking with `arm-linux-musleabihf-gcc` failed: exit status: 1
  |
  = note: "arm-linux-musleabihf-gcc" "/rust/lib/rustlib/arm-unknown-linux-musleabihf/lib/self-contained/crt1.o" "/rust/lib/rustlib/arm-unknown-linux-musleabihf/lib/self-contained/crti.o" "/rust/lib/rustlib/arm-unknown-linux-musleabihf/lib/self-contained/crtbegin.o" "/target/arm-unknown-linux-musleabihf/release/deps/cloud_gateway-1217d753b6b2adfa.cloud_gateway.f31181f6-cgu.0.rcgu.o" "-Wl,--as-needed" "-L" "/target/arm-unknown-linux-musleabihf/release/deps" "-L" "/target/release/deps" "-L" "/target/arm-unknown-linux-musleabihf/release/build/openssl-sys-5658aa5637f38c7c/out/openssl-build/install/lib" "-L" "/target/arm-unknown-linux-musleabihf/release/build/ring-ad69d615a5ca8a0b/out" "-L" "/rust/lib/rustlib/arm-unknown-linux-musleabihf/lib" "-Wl,-Bstatic" "/tmp/rustcFTTt8s/libring-06a9b6d9d5660bbb.rlib" "/tmp/rustcFTTt8s/libopenssl_sys-b779c6ee02f9f3a3.rlib" "-Wl,--start-group" "-lunwind" "/tmp/rustcFTTt8s/liblibc-955a2aaf479ae5c6.rlib" "-Wl,--end-group" "/rust/lib/rustlib/arm-unknown-linux-musleabihf/lib/libcompiler_builtins-3010074978d9ad33.rlib" "-Wl,-Bdynamic" "-latomic" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-nostartfiles" "-L" "/rust/lib/rustlib/arm-unknown-linux-musleabihf/lib" "-L" "/rust/lib/rustlib/arm-unknown-linux-musleabihf/lib/self-contained" "-o" "/target/arm-unknown-linux-musleabihf/release/deps/cloud_gateway-1217d753b6b2adfa" "-Wl,--gc-sections" "-static" "-no-pie" "-Wl,-zrelro" "-Wl,-znow" "-nodefaultlibs" "/rust/lib/rustlib/arm-unknown-linux-musleabihf/lib/self-contained/crtend.o" "/rust/lib/rustlib/arm-unknown-linux-musleabihf/lib/self-contained/crtn.o"
  = note: /tmp/rustcFTTt8s/libopenssl_sys-b779c6ee02f9f3a3.rlib(libcrypto-lib-threads_pthread.o): In function `CRYPTO_atomic_or':
          threads_pthread.c:(.text.CRYPTO_atomic_or+0x8): undefined reference to `__sync_or_and_fetch_8'
          /tmp/rustcFTTt8s/libopenssl_sys-b779c6ee02f9f3a3.rlib(libcrypto-lib-threads_pthread.o): In function `CRYPTO_atomic_load':
          threads_pthread.c:(.text.CRYPTO_atomic_load+0x20): undefined reference to `__sync_val_compare_and_swap_8'
          collect2: error: ld returned 1 exit status
          
  = help: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)
```

**Comment by Alexhuszagh** [comment] 2022-05-29 20:13
Are you using atomics in your crates? I'm guessing this is related to code using `std::sync::atomic::AtomicInt`?

**Comment by Alexhuszagh** [comment] 2022-07-02 17:26
Duplicate of #367.

**Comment by Alexhuszagh** [comment] 2022-07-03 21:32
This no longer replicates as of the latest main using the latest vendored OpenSSL. Note that you can't use the repository versions since those are linked to glibc. However, similar targets such as `armv5te-unknown-linux-musleabi` do fail with nearly identical errors, so if this reproduces later, I'll reopen this.

**Closed by Alexhuszagh** 2022-07-03 21:32 UTC
Labels: bug, duplicate, needs-information
