### ISSUE TITLE
armv7-unknown-linux-gnueabihf: sh: 1: cargo: not found

### ISSUE THREAD

**Issue by thavlik** [cross-rs/cross#437] opened 2020-06-27 13:23 UTC
Also tried with this Cross.toml, with no change:
```
[target.armv7-unknown-linux-gnueabihf]
image = "rustembedded/cross:armv7-unknown-linux-gnueabihf"
```
```
$ cross build --target armv7-unknown-linux-gnueabihf
Unable to find image 'rustembedded/cross:armv7-unknown-linux-gnueabihf' locally
armv7-unknown-linux-gnueabihf: Pulling from rustembedded/cross
e92ed755c008: Pull complete
b9fd7cb1ff8f: Pull complete
ee690f2d57a1: Pull complete
53e3366ec435: Pull complete
732605659179: Pull complete
21108c3ed136: Pull complete
030cdc7e51ee: Pull complete
111887b17cf4: Pull complete
0c5d70e1b7c6: Pull complete
cae016bf043c: Pull complete
afdf93775758: Pull complete
c3ae44d12984: Pull complete
1d020a9214bb: Pull complete
f5bea794ce4d: Pull complete
d66c18a188f8: Pull complete
6760aa4f7ae9: Pull complete
138d357e3459: Pull complete
a50866218188: Pull complete
Digest: sha256:624aaaf5a437c22aed39d340666e9f5b30c2c4a37e9bfcb7917f748ba7a5f2bc
Status: Downloaded newer image for rustembedded/cross:armv7-unknown-linux-gnueabihf
sh: 1: cargo: not found
```

**Comment by forslund** [comment] 2020-06-30 08:04
Had similar experience on armv7-unknown-linux-musleabihf

**Comment by forslund** [comment] 2020-06-30 11:45
In my case it may be a Windows thing...Docker needs to be allowed to share the folder (and me running docker inside docker makes this no less tricky)

**Comment by efx** [comment] 2020-07-25 17:48
This may be a duplicate of #260. There are some posts in that thread that are helpful for debugging.

**Comment by Alexhuszagh** [comment] 2022-07-02 21:26
> This may be a duplicate of #260. There are some posts in that thread that are helpful for debugging.

That seems to have evolved into numerous, unrelated issues including running docker in docker, Nix stores, remote docker usage, and WSL issues, of which this is unrelated.

**Closed** 2022-07-15 16:26 UTC
Labels: bug, duplicate
