### ISSUE TITLE
Upgrade Dockerfile.aarch64-unknown-linux-gnu base to ubuntu 20.04

### ISSUE THREAD

**Issue by Xuanwo** [cross-rs/cross#616] opened 2021-12-13 07:08 UTC
Hi, we recently met this issue: https://github.com/datafuselabs/databend/issues/3423

Is it OK to upgrade the from to `ubuntu:20.04` instead? I'm willing to make a PR for it.

**Comment by Emilgardis** [comment] 2021-12-13 08:39
See #591

**Comment by Alexhuszagh** [comment] 2022-05-28 16:00
I've also added documenting how to use these [newer images](https://github.com/cross-rs/cross/wiki/FAQ#newer-linux-versions) to the cross wiki so until the PR is merged, feel free to use these custom images.

**Comment by Alexhuszagh** [comment] 2022-07-02 21:18
Duplicate of #517.

**Closed by Alexhuszagh** 2022-07-02 21:18 UTC
Labels: container-images, breaking change
