### ISSUE TITLE
`GLIBC_2.29` not found in `ghcr.io/cross-rs/aarch64-unknown-linux-musl:0.2.5`

### ISSUE THREAD

**Issue by joepio** [cross-rs/cross#1436] opened 2024-02-05 12:09 UTC
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

I'm trying to build [AtomicServer](https://github.com/atomicdata-dev/atomic-server/issues/833) using cross `aarch64-unknown-linux-musl`, but since a couple of days (I think since 0.2.5) I'm getting `GLIBC_2.29' not found` errors:

```
Status: Downloaded newer image for ghcr.io/cross-rs/aarch64-unknown-linux-musl:0.2.5
warning: /project/lib/Cargo.toml: unused manifest key: bench.0.all-features
   Compiling libc v0.2.152
   Compiling log v0.4.17
   Compiling memchr v2.5.0
   Compiling serde v1.0.188
   Compiling lock_api v0.4.8
error: failed to run custom build command for `libc v0.2.152`

Caused by:
  process didn't exit successfully: `/target/release/build/libc-1dc77733931721b3/build-script-build` (exit status: 1)
  --- stderr
  /target/release/build/libc-1dc77733931721b3/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by /target/release/build/libc-1dc77733931721b3/build-script-build)
  /target/release/build/libc-1dc77733931721b3/build-script-build: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /target/release/build/libc-1dc77733931721b3/build-script-build)
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `log v0.4.17`
```

### What target(s) are you cross-compiling for?

aarch64-unknown-linux-musl

### Which operating system is the host (e.g computer cross is on) running?

- [ ] macOS
- [ ] Windows
- [X] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [X] x86_64 / AMD64
- [ ] arm32
- [ ] arm64 (including Mac M1)

### What container engine is cross using?

- [ ] docker
- [X] podman
- [ ] other container engine (specify in description)

### cross version

0.2.5

**Comment by Emilgardis** [comment] 2024-02-05 22:45
This is a duplicate of https://github.com/cross-rs/cross/issues/724

See that issue for potential fixes, the easiest being `cargo clean`

**Closed by Emilgardis** 2024-02-05 22:45 UTC
