### ISSUE TITLE
Glibc errors with v0.2.2

### ISSUE THREAD

**Issue by ravenclaw900** [cross-rs/cross#858] opened 2022-06-25 03:11 UTC
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

Cross returns glibc build script errors on aarch64-unknown-linux-musl and arm-unknown-linux-musleabihf with the new version.

### What target(s) are you cross-compiling for?

aarch64-unknown-linux-musl, arm-unknown-linux-musleabihf

### Which operating system is the host (e.g computer cross is on) running?

- [ ] macOS
- [ ] Windows
- [X] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [X] x86_64 / AMD64
- [ ] arm32
- [ ] arm64 (including Mac M1)

### What container engine is cross using?

- [X] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

v0.2.2

### Example

Armv6: https://github.com/ravenclaw900/DietPi-Dashboard/runs/7050663794
Aarch64: https://github.com/ravenclaw900/DietPi-Dashboard/runs/7050775525
Rebuild of previously working code: https://github.com/ravenclaw900/DietPi-Dashboard/runs/7051046368

### Additional information / notes

From https://github.com/cross-rs/cross/issues/724, running `cargo clean` or building without the cache didn’t help.

**Comment by Alexhuszagh** [comment] 2022-06-25 06:01
Can you give me detailed instructions on how to build your library? I've tried just the simple in the `backend` directory but I'm assuming I need to do something else.

```bash
cross build --release --target arm-unknown-linux-musleabihf --features compression
```

But if this does reproduce faithfully, this might be the best way we can diagnose and fix #724, so thank you.

**Comment by Alexhuszagh** [comment] 2022-06-25 06:09
This will take me a while to debug, and I'll be off tomorrow so it'll likely be Sunday or early next week, but it's not reproducing every time for `arm-unknown-linux-musleabihf` on my end.

I've run the following sequence:

```bash
git clone https://github.com/ravenclaw900/DietPi-Dashboard --depth 1
cd DietPi-Dashboard
cd src/frontend
yarn build
cd ../..
cp -r src/frontend/dist src/backend
cross build --release --target arm-unknown-linux-musleabihf --features compression
```

I'll try extensively debugging this, and sometimes issues arise when mixing toolchains so I'll try that too.

**Comment by Emilgardis** [comment] 2022-06-25 11:42
Related to #724, this one isn't solved with a clean however

**Comment by Emilgardis** [comment] 2022-06-25 12:07
The issue, I think, is that somehow, we're using `/target/release/build/dep-deadbeef/build-script-build` instead of `/target/<target>/release/build/dep-deadbeef/build-script-build`

**Comment by Emilgardis** [comment] 2022-06-25 12:51
Removing all `build-script-builds` in `target/release/deps` and `target/release/build` is enough.

I believe this is related https://github.com/rust-lang/cargo/issues/10367#issuecomment-1053678306

**Comment by ravenclaw900** [comment] 2022-06-25 15:44
That didn't seem to work: https://github.com/ravenclaw900/DietPi-Dashboard/runs/7054638003.

**Comment by Emilgardis** [comment] 2022-06-25 16:00
Sorry, I meant remove all dependencies of the buildscript, so remove every folder with a build-script. I just removed the full folders.

This is essentially a `cargo clean` but worse.

**Comment by ravenclaw900** [comment] 2022-06-25 17:08
Alright, deleting all the build folders and all the `.so` files let it compile.

**Comment by rafaelmaeuer** [comment] 2022-06-27 14:25
I had this error when building binaries for different platforms with a bash-script. Deleting `target/release` after every build solved it for me.

**Comment by Alexhuszagh** [comment] 2022-07-02 16:16
Closing as a duplicate of #724.

**Closed by Alexhuszagh** 2022-07-02 16:16 UTC
Labels: bug, duplicate

**Comment by hcldan** [comment] 2022-09-08 16:35
@Alexhuszagh I've looked through the contents of the linked issues (thank you, by the way, I missed your open issue).
What I'm not understanding here is that the build script is compiled in the docker container the first time... otherwise the first build wouldn't work, right?

On the subsequent build, the scripts look to have been recompiled, but cross didn't do it this time.
Is there no way for cross to get in front of that, or to make sure the build script is compiled in the container each time?
