### ISSUE TITLE
aarch64-linux: lower glibc version requirement to 2.17 (compatible with centos 7)

### ISSUE THREAD

**Issue by jszwedko** [cross-rs/cross#528] opened 2021-03-09 18:32 UTC
Similar to https://github.com/rust-embedded/cross/pull/501, I'm wondering how difficult it'd be to also lower the requirement for aarch64-unknown-linux-gnu to 2.17.

Notably I think the table entry is out-of-date:

aarch64-unknown-linux-gnu | 2.19 | 4.8.2 | ✓ | 4.1.0 | ✓
-- | -- | -- | -- | -- | --

At least when building my test binary, it seems to only include symbols from 2.17 and 2.18.

```
	linux-vdso.so.1 (0x0000ffffb1de6000)
	libdl.so.2 => /lib64/libdl.so.2 (0x0000ffffb1d46000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x0000ffffb1d11000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x0000ffffb1ce0000)
	libc.so.6 => /lib64/libc.so.6 (0x0000ffffb1b5a000)
	/lib/ld-linux-aarch64.so.1 (0x0000ffffb1da8000)

	Version information:
	./tmp:
		libc.so.6 (GLIBC_2.17) => /lib64/libc.so.6
		libc.so.6 (GLIBC_2.18) => /lib64/libc.so.6
		libgcc_s.so.1 (GCC_3.3) => /lib64/libgcc_s.so.1
		libgcc_s.so.1 (GCC_3.0) => /lib64/libgcc_s.so.1
		libgcc_s.so.1 (GCC_4.2.0) => /lib64/libgcc_s.so.1
		libpthread.so.0 (GLIBC_2.17) => /lib64/libpthread.so.0
		libdl.so.2 (GLIBC_2.17) => /lib64/libdl.so.2
	/lib64/libdl.so.2:
		ld-linux-aarch64.so.1 (GLIBC_PRIVATE) => /lib/ld-linux-aarch64.so.1
		ld-linux-aarch64.so.1 (GLIBC_2.17) => /lib/ld-linux-aarch64.so.1
		libc.so.6 (GLIBC_PRIVATE) => /lib64/libc.so.6
		libc.so.6 (GLIBC_2.17) => /lib64/libc.so.6
	/lib64/libpthread.so.0:
		ld-linux-aarch64.so.1 (GLIBC_2.17) => /lib/ld-linux-aarch64.so.1
		ld-linux-aarch64.so.1 (GLIBC_PRIVATE) => /lib/ld-linux-aarch64.so.1
		libc.so.6 (GLIBC_PRIVATE) => /lib64/libc.so.6
		libc.so.6 (GLIBC_2.17) => /lib64/libc.so.6
	/lib64/libgcc_s.so.1:
		libc.so.6 (GLIBC_2.17) => /lib64/libc.so.6
	/lib64/libc.so.6:
		ld-linux-aarch64.so.1 (GLIBC_2.17) => /lib/ld-linux-aarch64.so.1
		ld-linux-aarch64.so.1 (GLIBC_PRIVATE) => /lib/ld-linux-aarch64.so.1
```

**Comment by Ten0** [comment] 2022-05-22 14:49
This seems to be a duplicate of #455

**Comment by Emilgardis** [comment] 2022-05-22 16:19
For lowering glibc version I'd want something as described in #680. Thanks for doing some triaging @Ten0 <3

**Comment by Alexhuszagh** [comment] 2022-07-02 19:42
I think we can do this in https://github.com/cross-rs/cross-toolchains. It shouldn't be too hard to add an `aarch64-unknown-linux-gnu` target with an older glibc using crosstool-ng.

**Comment by Alexhuszagh** [comment] 2022-07-04 00:55
It's a little trickier than required since crosstool-ng has bugs with glibc for aarch64 below 2.25. See the discussion for [dockcross](https://github.com/dockcross/dockcross/issues/443). It seems `config.guess` is probably wrong, and this leads to the following error output:

```text
[INFO ]  =================================================================
[INFO ]  Installing C library headers & start files
[INFO ]    =================================================================
[INFO ]    Building for multilib 1/1: ''
[EXTRA]      Configuring C library
[ERROR]      checking sysdep dirs... configure: error: The aarch64 is not supported.
```

**Closed** 2022-09-06 17:42 UTC
Labels: enhancement, dynamic-linking, A-glibc
