### ISSUE TITLE
Support `cargo-auditable`

### ISSUE THREAD

**Issue by NobodyXu** [cross-rs/cross#1172] opened 2022-12-12 01:27 UTC
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar request
- [x] This feature could be solved with a [custom docker image](https://github.com/cross-rs/cross#custom-docker-images) (optional)

### Describe your request

I would like to use `cargo-auditable` along with `cross` to cross build a binary that is auditable.

I've already posted this on `cargo-auditable` https://github.com/rust-secure-code/cargo-auditable/issues/95 but @Shnatsel suggests me to file an issue here:

> Hmm. I think the best way forward is to file an issue on the cross issue tracker about potentially supporting cargo auditable. Basically a call to cargo auditable sets RUSTC_WORKSPACE_WRAPPER to itself, and saves the arguments it received into an environment variable so that the wrapper then recovers it. That's basically it as far as integration is concerned.

### Describe why this would be a good inclusion for `cross`

It will make it possible to use `cross` with `cargo-auditable`.

Additionally any program that uses `RUSTC_WORKSPACE_WRAPPER` can interoperate with `cross`.

**Comment by Shnatsel** [comment] 2022-12-12 01:37
`cargo auditable` sets not just `RUSTC_WORKSPACE_WRAPPER` but also other variables that need to be passed on.

I'm not at all familiar with Docker, but if `cross` builds binaries in Docker, I believe it _could_ be solved with a custom Docker image? You'd just have to configure the Docker image to [use cargo auditable as a drop-in replacement for Cargo](https://github.com/rust-secure-code/cargo-auditable/blob/master/REPLACING_CARGO.md).

**Comment by NobodyXu** [comment] 2022-12-12 01:43
> I'm not at all familiar with Docker, but if cross builds binaries in Docker, I believe it could be solved with a custom Docker image? You'd just have to configure the Docker image to [use cargo auditable as a drop-in replacement for Cargo](https://github.com/rust-secure-code/cargo-auditable/blob/master/REPLACING_CARGO.md).

Yep, I think it's possible.

> Alternatively you could use the [pre-build hook](https://github.com/cross-rs/cross#pre-build-hook) to install cargo auditable and set it up as a drop-in replacement for Cargo in all images, without having to build a custom image for every target.

I'd do that if `cargo-auditable` provides pre-built binaries.
It's hard to cache `cargo-auditable` that way.

**Comment by Shnatsel** [comment] 2022-12-12 01:48
We don't provide prebuilt binaries right now - perhaps that's something we ought to use `cross` for!

But you can easily create your own binary cache with [`cargo binstall`](https://crates.io/crates/cargo-binstall).

**Comment by NobodyXu** [comment] 2022-12-12 01:53
> But you can easily create your own binary cache with [cargo binstall](https://crates.io/crates/cargo-binstall).

Well, since `cargo-binstall` also supports quick install and quick install will build `cargo-auditable` if it is requested for many times, that will work though the first several builds would still be built-from-source.

P.S. I actually is one of the maintainers of `cargo-binstall` and is considering using `cargo-auditable` in it, but the CI already takes quite long so a bit hesitant to do it.

I wish `cross` supports pre-built hook for release only.

**Comment by Shnatsel** [comment] 2022-12-12 02:00
I believe that's what custom Docker images are for? You can build the image once, then cache it?

Alternatively we could have Github Actions build `cargo auditable` binaries and publish them to Github Releases for the most common platforms, so that there always would be prebuilt binaries to download. I'm currently occupied with other things but I'm happy to accept a PR. For `cargo auditable` this code is twice the fun because we first need to build the latest `cargo auditable` and then build the release artifact with it.

**Comment by NobodyXu** [comment] 2022-12-12 02:07
> I believe that's what custom Docker images are for? You can build the image once, then cache it?

Yeah, that's a reasonable solution.

> Alternatively we could have Github Actions build cargo auditable binaries and publish them to Github Releases for the most common platforms, so that there always would be prebuilt binaries to download.

I would definitely love that.

> I'm currently occupied with other things but I'm happy to accept a PR.

I would do so if I have time.
I also wish there's some kind of template for this https://github.com/cargo-bins/cargo-binstall/issues/309

> For cargo auditable this code is twice the fun because we first need to build the latest cargo auditable and then build the release artifact with it.

Oh bootstraping, but that can be cached right?
So not a big offender in CI runtime.

**Comment by Emilgardis** [comment] 2022-12-12 07:03
I think this is a duplicate of https://github.com/cross-rs/cross/issues/716, but we did not consider workspace wrappers in the current implementation, right @Alexhuszagh ?

**Comment by Shnatsel** [comment] 2022-12-12 14:51
Right now as long as you copy over the `cargo-auditable` binary into the container and invoke it appropriately, it should work. It is only a single binary with no external dependencies other than libc. 

The only potential issue I can see is the container's glibc being too old, which applies to all subcommands, and you could work around that by building with statically linked musl.

**Comment by Shnatsel** [comment] 2023-05-14 13:32
I see this has been closed as completed, but I can't find any recent pull requests that seem relevant. #716 is also still open.

Could you point me to the changes made to support it, and how can I make use of `cargo auditable` with cross?

**Comment by NobodyXu** [comment] 2023-05-14 14:29
@Shnatsel I think using pre-hook might work?
I close this

**Comment by NobodyXu** [comment] 2023-05-14 14:30
Sorry, I have reopened it.

**Comment by Shnatsel** [comment] 2023-05-14 14:40
A custom image or a pre-build hook can be used as a solutions. I suppose this can be closed in favor of #716 that tracks support for all subcommands.

**Closed** 2023-05-14 14:46 UTC
Labels: enhancement, feature-request

**Comment by Emilgardis** [comment] 2023-05-14 17:57
yes lets move it to #716

**Comment by Emilgardis** [comment] 2023-05-14 18:12
supposedly you can mark issues as duplicate, lets try


Duplicate of #716

**Comment by NobodyXu** [comment] 2023-05-15 23:22
> I believe that's what custom Docker images are for? You can build the image once, then cache it?
> 
> Alternatively we could have Github Actions build `cargo auditable` binaries and publish them to Github Releases for the most common platforms, so that there always would be prebuilt binaries to download. I'm currently occupied with other things but I'm happy to accept a PR. For `cargo auditable` this code is twice the fun because we first need to build the latest `cargo auditable` and then build the release artifact with it.

P.S. [cargo-quickinstall](https://github.com/cargo-bins/cargo-quickinstall) has been using `cargo-audit` to build pre-build artifacts since then and it can build `cargo-audit` with `cargo-audit`.
