### ISSUE TITLE
Option to disable host compiler fallback

### ISSUE THREAD

**Issue by mcandre** [cross-rs/cross#1232] opened 2023-03-26 21:39 UTC
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar request
- [ ] This feature could be solved with a [custom docker image](https://github.com/cross-rs/cross#custom-docker-images) (optional)

### Describe your request

As a DevOp, I want a CLI flag that disables host compiler fallback in the event that a Docker image is not found, in order to reduce mistakes during complex build pipelines.

Current behavior:

```console
$ cross build
[cross] warning: `cross` does not provide a Docker image for target aarch64-apple-darwin, specify a custom image in `Cross.toml`.
[cross] note: Falling back to `cargo` on the host.
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
```

Instead of `[cross] note: Falling back to `cargo` on the host.`, I want to see an error message.

Instead of continuing the build, I want cross to terminate immediately.

Instead of a successful exit code, I want a failure exit code emitted.

### Describe why this would be a good inclusion for `cross`

The fallback behavior can result in **accidents**, where engineers think they are building a cross-compiling artifacts for one platform, and end up generates artifacts that target the host platform instead.

I want no fallback. I want the build to fail early, and loudly.

**Comment by Emilgardis** [comment] 2023-03-26 21:56
This is a duplicate of #659 ! which is in the pipeline to be implemented for the next release!

**Closed** 2023-03-26 21:56 UTC
Labels: feature-request
