### ISSUE TITLE
Running cross on apple silicon with orbstack fails to download the containers.

### ISSUE THREAD

**Issue by laenzlinger** [cross-rs/cross#1288] opened 2023-07-17 17:46 UTC
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

Running cross on macOS arm64 with orbstack (https://docs.orbstack.dev/docker/) fails to download the docker image.

Orbstack uses Rosetta to run containers with foreign architectures. 

However I could not find a configuration to specify the container platform.

A workaround is described below

### What target(s) are you cross-compiling for?

aarch64-unknown-linux-gnu

### Which operating system is the host (e.g computer cross is on) running?

- [X] macOS
- [ ] Windows
- [ ] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [ ] x86_64 / AMD64
- [ ] arm32
- [X] arm64 (including Mac M1)

### What container engine is cross using?

- [ ] docker
- [ ] podman
- [X] other container engine (specify in description)

### cross version

cross 0.2.5

### Example

```
cross build --release --target aarch64-unknown-linux-gnu
Unable to find image 'ghcr.io/cross-rs/aarch64-unknown-linux-gnu:0.2.5' locally
0.2.5: Pulling from cross-rs/aarch64-unknown-linux-gnu
docker: no matching manifest for linux/arm64/v8 in the manifest list entries.
See 'docker run --help'.
make: *** [build] Error 125
```

### Additional information / notes

Workaround:

after downloading the image manually (forcing the platform) i can run the cross compiler successfulle:

```
docker pull ghcr.io/cross-rs/aarch64-unknown-linux-gnu:0.2.5 --platform linux/amd64
....
cross build --release --target aarch64-unknown-linux-gnu
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
   Compiling proc-macro2 v1.0.54
....
```

**Comment by Emilgardis** [comment] 2023-07-17 20:48
See https://github.com/cross-rs/cross/issues/1214#issuecomment-1452732222

This is a duplicate of #1214

**Closed by Emilgardis** 2023-07-17 20:48 UTC

**Comment by laenzlinger** [comment] 2023-07-17 21:14
Thanks @Emilgardis the link really helps!
