### ISSUE TITLE
jemalloc MADV_DONTNEED warning during build

### ISSUE THREAD

**Issue by ShaneMurphy2** [cross-rs/cross#1359] opened 2023-10-27 17:58 UTC
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

Whe I run `cross build --target aarch64-unknown-linux-gnu` on a simple project, I get:
```
<jemalloc>: MADV_DONTNEED does not work (memset will be used instead)
<jemalloc>: MADV_DONTNEED does not work (memset will be used instead)
<jemalloc>: MADV_DONTNEED does not work (memset will be used instead)
<jemalloc>: (This is the expected behaviour if you are running under QEMU)
<jemalloc>: (This is the expected behaviour if you are running under QEMU)
<jemalloc>: (This is the expected behaviour if you are running under QEMU)
```
This is spammed throughout the build process. 

### What target(s) are you cross-compiling for?

aarch64-unknown-linux-gnu

### Which operating system is the host (e.g computer cross is on) running?

- [X] macOS
- [ ] Windows
- [ ] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [ ] x86_64 / AMD64
- [ ] arm32
- [X] arm64 (including Mac M1)

### What container engine is cross using?

- [X] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

cross 0.2.5 (44011c8 2023-10-23)

### Example

```sh
cargo new arm
cd arm
cross build --target aarch64-unknown-linux-gnu
```
Output:
```
    Compiling arm v0.1.0 (/Users/Me/Something)
<jemalloc>: MADV_DONTNEED does not work (memset will be used instead)
<jemalloc>: (This is the expected behaviour if you are running under QEMU)
    Finished dev [unoptimized + debuginfo] target(s) in 2.85s
```

### Additional information / notes

I'm running Docker Desktop 4.24.2 (124339) and Rust 1.73.0. Also, I see this in docker desktop during a build:
![image](https://github.com/cross-rs/cross/assets/88051904/a2233aa6-cc22-4bbd-8aab-f127cccbd965)

**Comment by Emilgardis** [comment] 2023-10-27 18:05
this is a duplicate of https://github.com/cross-rs/cross/issues/1238

this is unfortunately expected behaviour

**Closed by Emilgardis** 2023-10-27 18:05 UTC

**Comment by ShaneMurphy2** [comment] 2023-10-27 18:07
> this is a duplicate of #1238
> 
> this is unfortunately expected behaviour

🤦 I'm bad at search apparently
