### ISSUE TITLE
cross is not building my project in containers.

### ISSUE THREAD

**Issue by jiaminglu** [cross-rs/cross#615] opened 2021-11-30 07:21 UTC
Because it says "the `x86_64-unknown-linux-gnu` target may not be installed".

How to debug cross itself? I'm running cross 0.2.1 on the new MacBook Pro with M1 Max. There is no this kind of problem on my old iMac.

**Comment by Emilgardis** [comment] 2021-11-30 08:06
Can you post the entire invocation and command output?

**Comment by jiaminglu** [comment] 2021-11-30 09:04
```
$ cross build --target x86_64-unknown-linux-gnu 
   Compiling cfg-if v1.0.0
   Compiling pin-project-lite v0.2.7
   Compiling bytes v1.1.0
   Compiling lazy_static v1.4.0
   Compiling futures-sink v0.3.17
   Compiling slab v0.4.4
   Compiling glob v0.3.0
   Compiling futures v0.1.31
   Compiling futures-io v0.3.17
   Compiling pin-utils v0.1.0
error[E0463]: can't find crate for `core`
  |
  = note: the `x86_64-unknown-linux-gnu` target may not be installed
  = help: consider downloading the target with `rustup target add x86_64-unknown-linux-gnu`

For more information about this error, try `rustc --explain E0463`.
error: could not compile `cfg-if` due to previous error
warning: build failed, waiting for other jobs to finish...
error[E0463]: can't find crate for `std`
  |
  = note: the `x86_64-unknown-linux-gnu` target may not be installed
  = help: consider downloading the target with `rustup target add x86_64-unknown-linux-gnu`

error: build failed
```
This output is after I manually uninstalled the target on the host machine, previously, it just fails at somewhere requires the gcc toolchain.

**Comment by jiaminglu** [comment] 2021-11-30 09:09
I've been using my own docker image for build. But even if I removed the Cross.toml, let it use its default configuration, it's not using the containers to build. I don't know if there is any other config files or environment variables that affects the behaviour of cross.

**Comment by wg** [comment] 2021-12-01 00:56
I'm running into this same issue too after building my own `rustembedded/cross:aarch64-unknown-linux-musl-0.2.1` image for aarch64 instead of x86_64. Looks like cross is requiring the `x86_64-unknown-linux-gnu` toolchain even on aarch64 systems, see: https://github.com/rust-embedded/cross/blob/master/src/rustc.rs#L62

If you comment out those three lines and rebuild cross it'll use the native `aarch64-unknown-linux-gnu` toolchain instead.

**Comment by jiaminglu** [comment] 2021-12-01 02:16
Finally I come to write a lightweight wrapper by myself, since running cargo in docker is as simple as just typing ```docker run --rm -v `pwd`:/project -w /project my_docker_image cargo build --release --target x86_64-unknown-linux-gnu```

**Comment by brooksmtownsend** [comment] 2021-12-03 15:28
I'm also running into this issue on an M1 Mac Pro. Works fine on x86 linux / mac but even with a custom `Cross.toml` it doesn't work.

To reproduce, clone https://github.com/wasmCloud/capability-providers, cd to `httpserver-rs`, run `make par-full`.

**Comment by michaelr0** [comment] 2021-12-16 05:06
I'm also having issues with this as well, I had noticed that the version 0.2.1 was tagged on the 20th of June 2020.
So I thought I might have a dig through the code and see if I could find a solution, but it seems that if you clone the master branch and `cargo build --release` then it seems to be working.

So I had a look at https://github.com/rust-embedded/cross/blob/master/CHANGELOG.md and I think these issues have been resolved in https://github.com/rust-embedded/cross/pull/489

Just need to build cross manually or I guess hopefully a new version with these updates/fixes gets tagged?

**Comment by TDHolmes** [comment] 2022-01-02 19:32
Thanks @michaelr0 installing latest unreleased fixed the issue for me. You can do `cargo install cross --git https://github.com/rust-embedded/cross --force` also

**Comment by michaelr0** [comment] 2022-01-02 19:52
> Thanks @michaelr0 installing latest unreleased fixed the issue for me. You can do `cargo install cross --git https://github.com/rust-embedded/cross --force` also

Awesome, thanks for that, I didn't know you could do that. I just manually built it and moved it to a bin path haha.

**Comment by Alexhuszagh** [comment] 2022-07-27 16:25
Does this reproduce for anyone as of the latest main or as of v0.2.4? I don't have an aarch64 machine to test this.

**Comment by Emilgardis** [comment] 2022-07-27 16:38
this was an issue with toolchain lookup, should have been solved with https://github.com/cross-rs/cross/pull/489 I believe

**Closed by Emilgardis** 2022-07-27 16:38 UTC
Labels: bug, A-aarch64-host
