### ISSUE TITLE
x86_64-unknown-linux-gnu Ubuntu version

### ISSUE THREAD

**Issue by lucasfernog** [cross-rs/cross#417] opened 2020-05-02 00:28 UTC
Can we use ubuntu 18.04 here? https://github.com/rust-embedded/cross/blob/master/docker/Dockerfile.x86_64-unknown-linux-gnu#L1

The reason is that i'm trying to install the `webkit2gtk-4.0` package, but it doesn't exist on 16.04.

**Comment by Alexhuszagh** [comment] 2022-05-27 15:53
This is addressed by #591, but this is a breaking change. Feel free to use the Dockerfile to build your own image and use the `Cross.toml` config to enable cross with more recent Ubuntu versions.

The relevant Dockerfile is [here](https://github.com/Alexhuszagh/cross/blob/2bafc9defa782ca9b628659cea09033170fbcaa9/docker/Dockerfile.x86_64-unknown-linux-gnu).

To build the image, do:

```bash
git clone https://github.com/Alexhuszagh/cross ahuszagh_cross
cd ahuszagh_cross
git checkout increment_versions
./build-docker-image.sh x86_64-unknown-linux-gnu
```

Then, add the following in your `Cross.toml`, so you use a local, custom built version of the dependency.

```toml
[target.x86_64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/x86_64-unknown-linux-gnu:local"
```

**Comment by Emilgardis** [comment] 2022-05-27 15:55
No it doesn't, `x86_64-unknown-linux-gnu` is not ubuntu, it's centos 7.

See #680

**Comment by Emilgardis** [comment] 2022-05-27 16:02
I should amend, it does in a way solve it, since you could copy the binaries from the first stage runner and hope that everything links up, but I think a more solid solution is the linked issue

**Comment by Alexhuszagh** [comment] 2022-05-27 16:03
Oh I believed they meant the original base image, since the Dockerfile they use uses CentOS 7.

**Comment by Emilgardis** [comment] 2022-05-27 16:07
Oh yeah, you're right. My bad!

https://github.com/cross-rs/cross/blob/95739b6d178d437d8fb7e908eb50e3a56ad0725c/docker/Dockerfile.x86_64-unknown-linux-gnu

perhaps a misunderstanding, or wanting to copy it

**Comment by Alexhuszagh** [comment] 2022-07-02 20:05
Duplicate of #517.

**Closed by Alexhuszagh** 2022-07-02 20:05 UTC
Labels: container-images, breaking change, A-x86
